### ISSUE TITLE
Roadmap to 0.1.0

### ISSUE THREAD

**Issue by hamlim** [srvr-rndr/srvr-rndr#4]
## Roadmap to 0.1.0

Below is an as complete list as possible of features / work I'd like to accomplish before calling this project as a semi-stable 0.1.0 release. (Stable enough to adopt it in side projects)

- [ ] Setup CI for the repo - #2
- [ ] Get the CLI working - #3
- [ ] Docs site deployed using the tools - #TODO
- [ ] A few more examples in the `examples/` dir
- [ ] More?
